version: "3"
services:
  selenium:
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444
      - 5900:5900
  app:
    build: ./app
    volumes:
      - ./app:/app
      - /dev/shm:/dev/shm
    environment:
      SELENIUM_URL: http://selenium:4444/wd/hub
    env_file: .env
    tty: true